### ISSUE TITLE
Octokit.ApiValidationException: Validation Failed

### ISSUE THREAD

**Issue by francinum** [tgstation/Tgstation.Server.ControlPanel#46]
Github API Error on connection to server.
https://hastebin.com/xefevecife.js

**Comment by francinum** [comment]
Issue arose after the repository linked to an instance was archived. Instance manually offlined through DB resolved issue.

**Comment by Cyberboss** [comment]
Mind linking the repo for reference?

**Comment by francinum** [comment]
https://github.com/DDMers/StarTrek13-Archived

The repo being renamed also should have been mentioned.

**Comment by Cyberboss** [comment]
Fixed recently
