### ISSUE TITLE
1.11.1 release is identifying itself as 1.10.0

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/Tgstation.Server.ControlPanel#61]
![image](https://user-images.githubusercontent.com/7069733/92315908-6f0b3500-efa1-11ea-8936-8a770ce5c0d2.png)

![image](https://user-images.githubusercontent.com/7069733/92315919-8a764000-efa1-11ea-938c-6b5e1ee8f709.png)
Downloaded today

**Comment by Cyberboss** [comment]
Fixed in https://github.com/tgstation/Tgstation.Server.ControlPanel/releases/tag/Tgstation.Server.ControlPanel-v1.11.2
