### ISSUE TITLE
An HTTP error occured: Unable to read data from transport connection: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by kcalbCube** [tgstation/Tgstation.Server.ControlPanel#92]
I apologize in advance if you do not accept this kind of questions here. In any case, my problem is specific to the TGS Control Panel desktop client, because the web client, in turn, works without any problems.
During the use of the panel, I periodically found myself unable to connect to the TGS, with the error that I indicated in the title, but after short(up to hour) time the connection always was established successfully.

Anyway, a few days ago the connection was not available to established at all, with the same error.
As I said, webpanel works fine, other people are also available to connect via TGS Control Panel.
I've already tried to remove any files from %APPDATA%/Tgstation.Server.ControlPanel

What can ever cause this problem?

**Comment by Cyberboss** [comment]
This isn't really the place for issues like these. The [Discussions]() page would be better for future reference.

This sounds like a possible routing/firewall issue. Have you tried with/without the `Use Plain HTTP` option checked? Are you able to browse directly to the TGS address in you web browser and get a response? Have you contacted your host to see if you have the correct address or potentially need to be whitelisted? Are you using a reverse proxy?

This error really just says the TGS server on the address you've entered can't be contacted, everything relating to that is outside the domain of this repo
